### PR TITLE
Fix obsolete escape method

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by orta** [comment]
Cool - looks good to me, nice tweaking

**Comment by revolter** [comment]
Looks like it was causing problems in fastlane, I hope. Could you please do another release?

**Comment by revolter** [comment]
@orta, Sorry if I'm being annoying, but, could you please do another release that includes this?

**Comment by orta** [comment]
I though I did

**Comment by orta** [comment]
weird

**Comment by orta** [comment]
Shipped as 1.1.2

**Pull request merged**
